services:
  postgres:
    image: postgres:17
    container_name: pg_db_dev
    ports: 
      - "${POSTGRES_PORT}:5432"
    restart: on-failure
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PGTZ=Asia/Ho_Chi_Minh
    env_file:
      - .env
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - task-management-v2-network
  redis: 
    image: redis:8-alpine
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    command: redis-server --appendonly yes
    volumes: 
      - redis_data_2:/data
    networks:
      - task-management-v2-network
volumes: 
  postgres_data_2:
  redis_data_2:
networks:
  task-management-v2-network:
    driver: bridge
